### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by tikibeni** [Le0nerdo/tiralabrav2#1]
# Projekti kloonattu 8.10.2021 klo 19:00

## Yleisesti toiminnoista

Käytin package managerina Yarnia. Asennus `yarn install`, käynnistys `yarn run localhost`, testiajo `yarn test` ja kattavuusraportin muodostus `yarn coverage` toimivat odotetusti. Ohjelma käynnistyi ohjeiden mukaisesti kohteeseen `localhost:8080`, jossa näkyi simulaatio pelistä. Toistaiseksi vaikuttaa siltä, että peli alkaa aina samasta puolivälipisteestä ja päättyy samaan lopputulokseen. Pelitilanteen sai resetoitua takaisin alkutilaan päivittämällä sivun. Olisi siistiä, jos pelaaja pystyisi ottamaan mittaa peli-AI:sta.

## Muuta

Koodi on siististi kommentoitua, minkä myötä se on varsin helppolukuista. Projekti on jäsennetty kivasti kansioihin. Mitään parannusehdotuksia en koodiin keksinyt, kun en ole JS:ään paljon koskenut. Ainut mikä pisti silmään oli käyttämätön luokka `RandomAI`, josta olitkin maininnut dokumentaatiossa. Projekti vaikuttaisi olevan hyvällä mallilla - tsemppiä jatkoon!

**Comment by Le0nerdo** [comment]
Ohjelman avaus tuo esille yhden testitapauksen siitä miten AI pelaa. AI aloittaa keskeneräisestä pelitilanteesta, koska se on liian hidas laskemaan aikaisempia tilanteita, koska vaihtoehtoja olisi liikaa.

Jos saan AI:n valmiiksi ennen kurssin loppupalautusta tai jos minua huvittaa, voin tehdä vaihtoehdon AI:ta vastaan pelaamiseen. AI tulee kuitenkin olemaan liian hyvä ja sitä vastaan pelaaminen on aika turhauttavaa. Varsinkin jos perfect AI aloittaa pelin, se voittaa aina riippumatta siitä miten sitä vastaan pelaa.
