### ISSUE TITLE
Vertaisarvio

### ISSUE THREAD

**Issue by Schamppu** [Le0nerdo/tiralabrav2#2]
# Vertaisarvio

### Ohjelma yleisesti

Testattu ohjelmaa. Ladattu ohjelma annetuilla komennoilla ja käynnistetty.

Ohjelma toimii hyvin ja käynnistyy hienosti annetuilla komennoilla. Mitään lisäsäätöä ei tarvittu.

Ohjelma näyttää myös toimivan, eli tekoäly pelaa itsekseen ja saa haluttuja tuloksia. Alkutilanne näyttää olevan ohjelmassa toistaiseksi aina sama.

Testit myös toimii ja ohjelmassa on runsaasti hyödyllisiä testejä. Coverage on myös lähes 100%, mikä on erittäin hyvä.

Ohjelma valitti faviconista, mutta kyseinen ongelma ei tuntunut vaikuttavat ohjelman toimintaan millään tavalla.

### Koodin arviointi

Hakemiston rakenne on erittäin hyvä. Tiedostot ovat järkevästi nimetty, ja niistä selviää hyvin mitä tiedosto sisältää.

Kommentteja on koodissa runsaasti, ja kommentit ovat todella pitkiä (itseäni jopa hieman häiritsevän pitkiä esim. GameState.js:ssä, osan näistä olisi voinut varmaan kirjoittaa lyhyemmin ja pidempiin selityksiin antaa linkki dokumentaatioon).

Koodi on selkeää, hyvin jäsenneltyä ja funktiot hyvän pituisia. Muuttujien nimeäminen on myös selkeää.

Testejä on kirjoitettu runsaasti, ja testien sisältö hyvin järkevää. Kaikki testit menee läpi ja toimii. Hienoa!

### Yhteenveto

Ohjelma näyttää olevan jo aikalailla valmis. Koodi on hyvää, hakemiston rakenne hyvä ja ohjelma toimii annetuilla ohjeilla. Ohjelmasta on vaikeaa löytää mitään negatiivista sanottavaa.

**Comment by Le0nerdo** [comment]
Voisin lisätä faviconin. Kyseessä on siis monessa selaimessa näkyvä välilehden pieni kuvake. En ole kertonut html tiedostossa sen olemassa olosta, mutta monet selaimet olettavat sen olevan tietyssä paikassa ja automaattisesti yrittävät löytää sitä sieltä.

Pitkät kommentit luokassa GameState.js ovat selityksiä bittioperaatioihin.  Ne ovat liian aika pitkiä, mutta en näe niiden lyheentämistä isoksi prioriteetiksi. Pidän tärkeänä, että kommentti on koodissa oikean rivin kohdalla.
